package dao; import java.sql.*; import model.Item; import util.db;
public class ItemDAO {
    private void print(ResultSet rs)throws Exception{System.out.println(rs.getInt("id")+" | "+rs.getString("name")+" | "+rs.getString("category")+" | "+rs.getString("brand")+" | Rs."+rs.getDouble("price")+" | Stock:"+rs.getInt("stock")+" | "+rs.getString("added_date"));}
    public boolean add(Item it){try{PreparedStatement ps=db.getConnection().prepareStatement("INSERT INTO items(name,category,brand,price,stock,added_date)VALUES(?,?,?,?,?,?)");ps.setString(1,it.getName());ps.setString(2,it.getCategory());ps.setString(3,it.getBrand());ps.setDouble(4,it.getPrice());ps.setInt(5,it.getStock());ps.setString(6,it.getAddedDate());return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void viewAll(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM items").executeQuery();boolean f=false;while(rs.next()){f=true;print(rs);}if(!f)System.out.println("No items.");}catch(Exception e){}}
    public void searchById(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("SELECT * FROM items WHERE id=?");ps.setInt(1,id);ResultSet rs=ps.executeQuery();if(rs.next())print(rs);else System.out.println("Not found.");}catch(Exception e){}}
    public void searchByCategory(String cat){try{PreparedStatement ps=db.getConnection().prepareStatement("SELECT * FROM items WHERE category=?");ps.setString(1,cat);ResultSet rs=ps.executeQuery();boolean f=false;while(rs.next()){f=true;print(rs);}if(!f)System.out.println("None.");}catch(Exception e){}}
    public boolean updateStock(int id,int stock){try{PreparedStatement ps=db.getConnection().prepareStatement("UPDATE items SET stock=? WHERE id=?");ps.setInt(1,stock);ps.setInt(2,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public boolean delete(int id){try{PreparedStatement ps=db.getConnection().prepareStatement("DELETE FROM items WHERE id=?");ps.setInt(1,id);return ps.executeUpdate()>0;}catch(Exception e){return false;}}
    public void count(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT COUNT(*) FROM items").executeQuery();if(rs.next())System.out.println("Total Items: "+rs.getInt(1));}catch(Exception e){}}
    public void generateBill(int id,int qty){try{PreparedStatement ps=db.getConnection().prepareStatement("SELECT * FROM items WHERE id=?");ps.setInt(1,id);ResultSet rs=ps.executeQuery();if(rs.next()){double p=rs.getDouble("price");System.out.println("--- BILL ---");System.out.println("Item: "+rs.getString("name"));System.out.println("Qty: "+qty+" x Rs."+p+" = Rs."+(qty*p));}else System.out.println("Item not found.");}catch(Exception e){}}
    public void sortByPrice(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM items ORDER BY price DESC").executeQuery();while(rs.next())print(rs);}catch(Exception e){}}
    public void outOfStock(){try{ResultSet rs=db.getConnection().prepareStatement("SELECT * FROM items WHERE stock=0").executeQuery();boolean f=false;System.out.println("Out of Stock Items:");while(rs.next()){f=true;print(rs);}if(!f)System.out.println("None.");}catch(Exception e){}}
}
